name: Changelog CI

on:
  push:
    branches:
      - main
      - insider

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.0.0
        with:
          changelog_filename: /src/static/changelog.md
          config_file: /changelog-ci-config.yaml
          release_version: 0.1
